### ISSUE TITLE
Option for only 1 key per game per user

### ISSUE THREAD

**Issue by ezelkow1** [ezelkow1/discord-key-bot#24]
Requested feature:

To have a way to limit keys to only 1 per game, per user. As of now Im thinking of this being an on/off type feature with a separate database of users with a list of what games they have taken. Would probably be the least intrusive to existing functionality and keep it separated from the keys themselves

**Comment by honzapatCZ** [comment]
Yes tahats what i meant.

**Comment by ezelkow1** [comment]
Addressed in ^

You should be able to either build it or download one of the releases. Give it a shot and let me know if that works for you. You just have to specify a "UserFile" in the conf and it will start storing usernames along with the names of games they have taken in it and prevent them from taking one that they already have done
