### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by MCRImagineering** [ezelkow1/discord-key-bot#37]
Hi, I recently downloaded the bot but doesn't seem like the .exe file actually works. Or am I doing something wrong?

**Comment by ezelkow1** [comment]
You have to make sure that the config is all setup properly first.  There is a config.json file you have to modify with your own information before it can start up properly

**Comment by d86592** [comment]
how do I start it, it says -c isn't a command?

**Comment by d86592** [comment]
the config is set up

**Comment by ezelkow1** [comment]
Just as an example
F:\Downloads\discord-key-bot.v1.5.Win64>discord-key-bot.exe -c conf.json
Db File does not exist, creating
error opening connection, websocket: close 4004: Authentication failed.

though mine fails since I didnt setup this conf, just using the example one from the zip file since I normally run the bot on linux so thats where I have it all setup

**Comment by d86592** [comment]
How do I run this on linux

**Comment by ezelkow1** [comment]
> 
> 
> How do I run this on linux

You have to have one of the releases unpacked somewhere, and then run it with -c conf.json, i.e. this how I have it setup to run on my raspberry pi:
/home/pi/keybot/discord-key-bot -c /home/pi/keybot/conf.json

**Comment by d86592** [comment]
Sorry for asking so many questions but, how do i get an unpacked version

**Comment by d86592** [comment]
Sorry, I got it unpacked, but where would I unpack it to?

**Comment by d86592** [comment]
I got it all on there but it will not identity the discord-key-bot folder as a directory! How do i fix that file?

**Comment by ezelkow1** [comment]
discord-key-bot is not a directory, it is a linux executable. You have to unpack them with tar -xvzf release.tgz (whatever the name is).  This will unpack the executable and the example configuration file to wherever you have the tgz.

Then you can run it with ./discord-key-bot -c conf.json

If for some reason the permissions are messed up you can do, chmod 777 discord-key-bot, that will make it read/write/execute for any user.

I have also uploaded a 32bit build in case you do actually need a 32bit one

**Comment by d86592** [comment]
I am using that build, thanks for adding it!
